export const words = [
  { word: "IRLANDA", hint: "LUGARES" },
  { word: "EQUADOR", hint: "LUGARES" },
  { word: "CHILE", hint: "LUGARES" },
  { word: "INDONESIA", hint: "LUGARES" },
  { word: "MALDIVAS", hint: "LUGARES" },
  { word: "INGLATERRA", hint: "LUGARES" },
  { word: "GROELANDIA", hint: "LUGARES" },
  { word: "UZBEQUISTAO", hint: "LUGARES" },
  { word: "CREGUENHEM", hint: "LUGARES" },

  { word: "BICICLETA", hint: "TRANSPORTE" },
  { word: "LANCHA", hint: "TRANSPORTE" },
  { word: "NAVIO", hint: "TRANSPORTE" },
  { word: "TELEFERICO", hint: "TRANSPORTE" },
  { word: "MOTOCICLETA", hint: "TRANSPORTE" },
  { word: "BARCO", hint: "TRANSPORTE" },
  { word: "AERONAVE", hint: "TRANSPORTE" },
  { word: "TREM", hint: "TRANSPORTE" },
  { word: "CAIAQUE", hint: "TRANSPORTE" },
  { word: "FUNICULAR", hint: "TRANSPORTE" },

  { word: "XICARA", hint: "OBJETOS" },
  { word: "MOEDA", hint: "OBJETOS" },
  { word: "ESPARADRAPO", hint: "OBJETOS" },
  { word: "SINO", hint: "OBJETOS" },
  { word: "CHUVEIRO", hint: "OBJETOS" },
  { word: "TAMBORETE", hint: "OBJETOS" },
  { word: "LAMPADA", hint: "OBJETOS" },
  { word: "BOCAL", hint: "OBJETOS" },
  { word: "CORTINA", hint: "OBJETOS" },
  { word: "LAPIS", hint: "OBJETOS" },

  { word: "MELANCIA", hint: "ALIMENTOS" },
  { word: "AMENDOIM", hint: "ALIMENTOS" },
  { word: "ESFIRRA", hint: "ALIMENTOS" },
  { word: "GOROROBA", hint: "ALIMENTOS" },
  { word: "JANTAR", hint: "ALIMENTOS" },
  { word: "SABOROSO", hint: "ALIMENTOS" },
  { word: "DESJEJUM", hint: "ALIMENTOS" },
  { word: "MASTIGAR", hint: "ALIMENTOS" },
  { word: "ENGOLIR", hint: "ALIMENTOS" },
  { word: "DOCERIA", hint: "ALIMENTOS" },

  { word: "DRAGAO", hint: "ANIMAIS" },
  { word: "GALINHA", hint: "ANIMAIS" },
  { word: "PAVAO", hint: "ANIMAIS" },
  { word: "CAMELO", hint: "ANIMAIS" },
  { word: "PERU", hint: "ANIMAIS" },
  { word: "ZEBRA", hint: "ANIMAIS" },
  { word: "DROMEDARIO", hint: "ANIMAIS" },
  { word: "CALANGO", hint: "ANIMAIS" },
  { word: "SAGUI", hint: "ANIMAIS" },
  { word: "LAGARTIXA", hint: "ANIMAIS" },
  { word: "HIPOPOTAMO", hint: "ANIMAIS" },
];
